import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Grid, Box, Button, IconButton } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import styles from '../styles/Home.module.css'
import { useEffect, useState} from 'react'
import { nanoid } from 'nanoid'
import Noteslist from './../components/NotesList';
import Search from './../components/Search';
import AddNote from './../components/AddNote';
import EditNote from './../components/EditNote';
import { Note } from './../types/general';

const Home: NextPage = () => {
  const [showAddNote, setShowAddNote] = useState<boolean>(false)
  const [notes, setNotes] = useState<Array<Note>>([{
    id: "EkhwqqmsRwlsObUdPjElT",
    text: "initial note",
    date: "28.12.2021"
  }])
  const [currentNote, setCurrentNote] = useState<Note>({
    id: "EkhwqqmsRwlsObUdPjElT",
    text: "initial note",
    date: "28.12.2021"
  })
	const [searchText, setSearchText] = useState('')
	// useEffect(()=>{
	// 	const savedNotes = JSON.parse(localStorage.getItem('react-notes-app-data'))
    
	// 	if(savedNotes)
	// 	{
	// 		setNotes(savedNotes)
	// 	}
	// },[])

	const addNote = (text:string) => {
		const date = new Date()
		const newNote:Note = {
			id:nanoid(),
			text:text,
			date:date.toLocaleDateString()
		}
		const newNotes:Array<Note> = [...notes, newNote]
		setNotes(newNotes)
	}

  const selectNote = (noteId:string) => {
    setShowAddNote(false)
    let note = notes.filter((note)=> note.id === noteId)[0]
    console.log('note', note)
		setCurrentNote(note)
	}

  const editNote = (noteId:string, text:string) => {
    setShowAddNote(false)
    let note = notes.filter((note)=> note.id === noteId)[0]
    let newNotes = notes.slice();
    newNotes.forEach((item) => {
      if(item.id === noteId) {
        item.text = text
      }
    })
		setCurrentNote(note)
		setNotes(newNotes)
	}

	const deleteNote = (id:string) => {
		const newNotes = notes.filter((note)=> note.id !== id)
		setNotes(newNotes)
	}

  const toggleAddNote = (state:boolean) => {

    setShowAddNote(state)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        <main className={styles.main}>
          <h1 className={styles.title}>
            Note app
          </h1>
          <Box sx={{ 
            display: 'flex', 
            alignItems: 'baseline', 
            justifyContent: 'flex-end',
            my: 1.5
            }}>
            <Button sx={{ mx: 1.5}} variant="contained" onClick={()=>toggleAddNote(true)} endIcon={<AddIcon />}>
              Add note
            </Button>
            <Search handleSearchNote={setSearchText} />
          </Box>
          <Grid container spacing={2}>
            <Grid item xs={4}>
              <Noteslist 
                notes={notes.filter((note)=> note.text.toLowerCase().includes(searchText))} 
                currentNoteId={showAddNote? '' : currentNote.id} 
                handleEdit={selectNote} 
                handleDelete={deleteNote} 
              />
            </Grid>
            <Grid item xs={8}>
              {!showAddNote ?
                <EditNote handleSave={addNote} handleEdit={editNote} handleDelete={deleteNote} note={currentNote}/>
              : <AddNote handleSave={addNote}/>
            }
            </Grid>
          </Grid>
        </main>
      

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

